namespace ArchitectsJourney.Application.Events;

/// <summary>
/// Base record for all events flowing through the platform Event Bus.
/// Immutable by design — all properties are init-only.
/// Corresponds to the DomainEvent envelope defined in Document 10, Section 5.
///
/// SequenceNumber is NOT part of this record.
/// The Event Bus assigns sequence numbers internally and tracks them in the Audit Store.
/// This keeps the event envelope truly immutable after publication.
/// </summary>
public abstract record DomainEvent
{
    /// <summary>
    /// Universally unique identifier for this specific event.
    /// Generated by the publisher at construction time.
    /// Never reused. Duplicate detection enforced by the Event Bus.
    /// </summary>
    public Guid EventId { get; init; } = Guid.NewGuid();

    /// <summary>
    /// SCREAMING_SNAKE_CASE identifier for the event type.
    /// Must correspond to a constant in <see cref="EventTypes"/>.
    /// </summary>
    public abstract string EventType { get; }

    /// <summary>
    /// Logical grouping category for subscription routing.
    /// </summary>
    public abstract EventCategory EventCategory { get; }

    /// <summary>
    /// Payload schema version. Used by the Schema Registry for validation.
    /// Format: MAJOR.MINOR (e.g., "1.0").
    /// </summary>
    public abstract string SchemaVersion { get; }

    /// <summary>
    /// Determines processing order in the Event Bus priority queue.
    /// </summary>
    public abstract EventPriority Priority { get; }

    /// <summary>
    /// Timestamp set by the publisher at event construction.
    /// Not set by the Event Bus — preserves the publisher's causal time.
    /// </summary>
    public DateTimeOffset ProducedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Identifier of the registered subsystem that produced this event.
    /// Must appear in the Publisher Registry.
    /// </summary>
    public abstract string ProducerId { get; }

    /// <summary>
    /// The active game session this event belongs to.
    /// All events within a session share this identifier.
    /// </summary>
    public Guid SessionId { get; init; }

    /// <summary>
    /// The active Playthrough aggregate this event affects.
    /// Null for system-level events before session creation.
    /// </summary>
    public Guid? PlaythroughId { get; init; }

    /// <summary>
    /// The active mission this event belongs to.
    /// Null for system-level events before mission load.
    /// </summary>
    public string? MissionId { get; init; }

    /// <summary>
    /// The EventId of the event that directly caused this event.
    /// Null if this is a root event (player action or system lifecycle).
    /// </summary>
    public Guid? CausationId { get; init; }

    /// <summary>
    /// The EventId of the root event in the causal chain.
    /// For root events: equals EventId.
    /// For derived events: equals the root ancestor's EventId.
    /// Enables complete causal chain reconstruction from the Audit Store.
    /// </summary>
    public Guid CorrelationId { get; init; }

    /// <summary>
    /// Creates a root-event correlation context (causation = null, correlation = self).
    /// Call this when constructing an event that is NOT derived from another event.
    /// </summary>
    public static (Guid CorrelationId, Guid? CausationId) RootContext()
    {
        var id = Guid.NewGuid();
        return (id, null);
    }

    /// <summary>
    /// Creates a derived-event correlation context from a parent event.
    /// Call this when constructing an event caused by processing another event.
    /// </summary>
    public static (Guid CorrelationId, Guid? CausationId) DerivedFrom(DomainEvent parent)
    {
        ArgumentNullException.ThrowIfNull(parent);
        return (parent.CorrelationId, parent.EventId);
    }
}
